apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ticketing
  annotations:
    github.com/project-slug: KVoronovich/ticketing
spec:
  type: other
  lifecycle: unknown
  owner: guests
